development:
  adapter: sqlite3
  database: var/db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: var/db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: var/db/production.sqlite3
  pool: 5
  timeout: 5000
